places = [
    # --- CAFÉS ---
    {
        "name": "Little Fern",
        "description": "Café de estilo neozelandés con excelente brunch y café de especialidad.",
        "category": "Cafe",
        "latitude": 41.3986,
        "longitude": 2.1965,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Bar Sopa",
        "description": "Local vegetariano y vegano muy tranquilo y espacioso para ir con perro.",
        "category": "Cafe",
        "latitude": 41.4018,
        "longitude": 2.1932,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Espai Joliu",
        "description": "Concept store llena de plantas donde el café y los perros son bienvenidos.",
        "category": "Cafe",
        "latitude": 41.3982,
        "longitude": 2.1934,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Orval",
        "description": "Cafetería de especialidad minimalista con ambiente industrial.",
        "category": "Cafe",
        "latitude": 41.3975,
        "longitude": 2.1915,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Nomad Coffee Lab",
        "description": "Tostadores locales con un espacio abierto ideal para una parada rápida.",
        "category": "Cafe",
        "latitude": 41.4011,
        "longitude": 2.1955,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Skye Coffee Co.",
        "description": "Café servido desde una furgoneta Citroën HY de 1972 dentro de una nave.",
        "category": "Cafe",
        "latitude": 41.3989,
        "longitude": 2.1921,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    # --- RESTAURANTES ---
    {
        "name": "101 Dim Sum - Poblenou",
        "description": "Fusión asiática y dim sum artesanal en plena Rambla del Poblenou.",
        "category": "Restaurant",
        "latitude": 41.4035,
        "longitude": 2.2021,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Nolita Poblenou",
        "description": "Pizzas estilo Nueva York y entrantes creativos en un local moderno.",
        "category": "Restaurant",
        "latitude": 41.4022,
        "longitude": 2.2015,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Timesburg Poblenou",
        "description": "Hamburguesas de autor con una terraza amplia y cómoda.",
        "category": "Restaurant",
        "latitude": 41.4015,
        "longitude": 2.1985,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Popolo Nuovo",
        "description": "Restaurante italiano que permite mascotas en el interior.",
        "category": "Restaurant",
        "latitude": 41.4028,
        "longitude": 2.2005,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Warike Project",
        "description": "Comida callejera peruana con mucha personalidad y trato genial a perros.",
        "category": "Restaurant",
        "latitude": 41.4031,
        "longitude": 2.1972,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Hideout Burger",
        "description": "Smash burgers de referencia en el barrio.",
        "category": "Restaurant",
        "latitude": 41.4005,
        "longitude": 2.1968,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "La Taqueria",
        "description": "Tacos auténticos con terraza y ambiente muy relajado.",
        "category": "Restaurant",
        "latitude": 41.4012,
        "longitude": 2.1991,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Madrelievito",
        "description": "Pizza napolitana tradicional; suelen tener agua para los peludos.",
        "category": "Restaurant",
        "latitude": 41.4025,
        "longitude": 2.1989,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Brisa Sin Prisa",
        "description": "Cocina mediterránea de mercado con buena terraza.",
        "category": "Restaurant",
        "latitude": 41.4033,
        "longitude": 2.2028,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Blu Bar",
        "description": "Pizzas plant-based y bowls con una terraza enorme frente al parque.",
        "category": "Restaurant",
        "latitude": 41.3992,
        "longitude": 2.2038,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Bitácora",
        "description": "Tapas clásicas del barrio con ambiente familiar y pet friendly.",
        "category": "Restaurant",
        "latitude": 41.3985,
        "longitude": 2.2025,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Can Pineda",
        "description": "Clásico de la zona para cocina catalana de alto nivel.",
        "category": "Restaurant",
        "latitude": 41.4111,
        "longitude": 2.1932,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Els Tres Porquets",
        "description": "Platillos y vinos excelentes en un ambiente muy acogedor.",
        "category": "Restaurant",
        "latitude": 41.4085,
        "longitude": 2.1965,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Recasens",
        "description": "Embutidos y quesos en un local histórico precioso.",
        "category": "Restaurant",
        "latitude": 41.4019,
        "longitude": 2.2031,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Koh Poblenou",
        "description": "Platos de inspiración asiática en un local muy estético.",
        "category": "Restaurant",
        "latitude": 41.4001,
        "longitude": 2.1952,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    # --- PIPICANES Y PARQUES ---
    {
        "name": "Pipí Can Jardins de Gandhi",
        "description": "Área vallada específica para perros con bancos y sombra.",
        "category": "Pipí can",
        "latitude": 41.4061,
        "longitude": 2.2105,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Parc del Poblenou Dog Area",
        "description": "Gran zona verde junto al mar ideal para socializar.",
        "category": "Park",
        "latitude": 41.3995,
        "longitude": 2.2062,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Parc del Centre del Poblenou",
        "description": "Pipican vallado dentro del parque diseñado por Jean Nouvel.",
        "category": "Pipí can",
        "latitude": 41.4068,
        "longitude": 2.1981,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Parc del Clot",
        "description": "Parque histórico con arquerías romanas y zona de recreo canino.",
        "category": "Park",
        "latitude": 41.4082,
        "longitude": 2.1895,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Platja de Llevant (Zona Perros)",
        "description": "Sección habilitada de la playa para perros (temporada verano).",
        "category": "Fun",
        "latitude": 41.4075,
        "longitude": 2.2155,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Jardins de Joana Tomàs",
        "description": "Pequeño jardín de barrio con zona habilitada para perros.",
        "category": "Pipí can",
        "latitude": 41.4045,
        "longitude": 2.1925,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Parc Carles I",
        "description": "Espacio abierto muy amplio entre Vila Olímpica y Poblenou.",
        "category": "Park",
        "latitude": 41.3912,
        "longitude": 2.1945,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Plaça Julio González",
        "description": "Pipican urbano para paradas rápidas.",
        "category": "Pipí can",
        "latitude": 41.3965,
        "longitude": 2.1978,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Parc de la Diagonal Mar",
        "description": "Parque vanguardista con recinto cerrado para perros.",
        "category": "Park",
        "latitude": 41.4092,
        "longitude": 2.2131,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Jardins de Simone de Beauvoir",
        "description": "Zona verde tranquila con espacios aptos para pasear.",
        "category": "Park",
        "latitude": 41.4032,
        "longitude": 2.1912,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    # --- ALOJAMIENTOS ---
    {
        "name": "The Hoxton, Poblenou",
        "description": "Hotel de diseño que ofrece camas y cuencos para perros.",
        "category": "Lodging",
        "latitude": 41.4025,
        "longitude": 2.1915,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "Travelodge Barcelona Poblenou",
        "description": "Opción económica y funcional que acepta mascotas con suplemento.",
        "category": "Lodging",
        "latitude": 41.4005,
        "longitude": 2.2001,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "Hostal Poble Nou",
        "description": "B&B boutique donde las mascotas son muy bienvenidas.",
        "category": "Lodging",
        "latitude": 41.4018,
        "longitude": 2.2038,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Ibis Styles City Bogatell",
        "description": "Hotel moderno con habitaciones temáticas pet-friendly.",
        "category": "Lodging",
        "latitude": 41.3945,
        "longitude": 2.1922,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "Novotel Barcelona City",
        "description": "Ubicado en Glòries, permite perros de hasta cierto peso.",
        "category": "Lodging",
        "latitude": 41.4038,
        "longitude": 2.1901,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "SB Diagonal Zero",
        "description": "Hotel de lujo cerca del Fòrum con política dog-friendly.",
        "category": "Lodging",
        "latitude": 41.4115,
        "longitude": 2.2195,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "Hesperia del Mar",
        "description": "Hotel frente a la playa que admite mascotas pequeñas.",
        "category": "Lodging",
        "latitude": 41.4012,
        "longitude": 2.2091,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    # --- TIENDAS Y NEGOCIOS ---
    {
        "name": "Kiwoko Poblenou",
        "description": "Tienda gigante de productos para animales y peluquería.",
        "category": "Store",
        "latitude": 41.4022,
        "longitude": 2.2025,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Tiendanimal Glòries",
        "description": "Suministros y servicios de salud dentro del centro comercial.",
        "category": "Store",
        "latitude": 41.4045,
        "longitude": 2.1885,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Westfield Glòries",
        "description": "Centro comercial al aire libre totalmente pet-friendly.",
        "category": "Store",
        "latitude": 41.4042,
        "longitude": 2.1895,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Mascota Avenue",
        "description": "Centro veterinario y boutique de accesorios en la zona.",
        "category": "Business",
        "latitude": 41.4055,
        "longitude": 2.1912,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Clínica Veterinària Poblenou",
        "description": "Hospital animal de referencia en el barrio.",
        "category": "Business",
        "latitude": 41.4021,
        "longitude": 2.2018,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Amics Bonics",
        "description": "Peluquería canina con un trato excelente y estilismo.",
        "category": "Business",
        "latitude": 41.3968,
        "longitude": 2.2012,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "IKEA Glòries",
        "description": "Se permiten perros en tienda (no en la zona de restaurante).",
        "category": "Store",
        "latitude": 41.4035,
        "longitude": 2.1882,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Zara Diagonal Mar",
        "description": "La tienda permite la entrada de perros atados.",
        "category": "Store",
        "latitude": 41.4102,
        "longitude": 2.2165,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Barkcelona",
        "description": "Tienda gourmet y pastelería artesanal para perros.",
        "category": "Store",
        "latitude": 41.4031,
        "longitude": 2.1995,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Veterinaria del Mar",
        "description": "Hospital 24h especializado en medicina interna y cirugía.",
        "category": "Business",
        "latitude": 41.3925,
        "longitude": 2.1975,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Bichos Poblenou",
        "description": "Tienda local de barrio con alimentación natural.",
        "category": "Store",
        "latitude": 41.4042,
        "longitude": 2.2032,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "L'Arc de Noè",
        "description": "Tienda de accesorios y productos de higiene canina.",
        "category": "Store",
        "latitude": 41.4051,
        "longitude": 2.2015,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Peluquería Canina Dr. Trueta",
        "description": "Corte y baño cerca del Parque del Poblenou.",
        "category": "Business",
        "latitude": 41.3972,
        "longitude": 2.2021,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Sant Martí Veterinària",
        "description": "Consultas generales y medicina preventiva.",
        "category": "Business",
        "latitude": 41.4152,
        "longitude": 2.1988,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Pet Shop Diagonal Mar",
        "description": "Tienda especializada en el centro comercial Diagonal Mar.",
        "category": "Store",
        "latitude": 41.4105,
        "longitude": 2.2158,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    # --- GLÒRIES ---
    {
        "name": "Honest Greens Glòries",
        "description": "Comida real y saludable. Terraza muy amplia y pet-friendly ideal para ir con el perro.",
        "category": "Restaurant",
        "latitude": 41.4039,
        "longitude": 2.1892,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "The Coffee House Barcelona",
        "description": "Café de especialidad justo al lado del DHUB. Muy tranquilo para trabajar con tu perro al lado.",
        "category": "Cafe",
        "latitude": 41.4025,
        "longitude": 2.1880,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Museu del Disseny (Jardines)",
        "description": "Espacios exteriores del DHUB. Perfectos para pasear y descansar en el césped.",
        "category": "Park",
        "latitude": 41.4022,
        "longitude": 2.1872,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Mercat dels Encants",
        "description": "El mercado de pulgas más famoso. Los perros son bienvenidos en los pasillos abiertos.",
        "category": "Store",
        "latitude": 41.4015,
        "longitude": 2.1865,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Pipican Glòries Norte",
        "description": "Zona vallada renovada recientemente con elementos de juego para perros.",
        "category": "Pipí can",
        "latitude": 41.4050,
        "longitude": 2.1885,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "La Tagliatella Glòries",
        "description": "Cadena italiana con terraza exterior protegida donde aceptan mascotas.",
        "category": "Restaurant",
        "latitude": 41.4045,
        "longitude": 2.1898,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Starbucks Glòries",
        "description": "Terraza exterior amplia. Clásico para un café rápido con tu mascota.",
        "category": "Cafe",
        "latitude": 41.4041,
        "longitude": 2.1890,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Jardins de Ca l'Aranyó",
        "description": "Pequeño oasis verde rodeado de edificios tecnológicos de la UPF.",
        "category": "Park",
        "latitude": 41.4031,
        "longitude": 2.1935,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Pure Cuisine Glòries",
        "description": "Fusión asiática saludable en la zona abierta del centro comercial.",
        "category": "Restaurant",
        "latitude": 41.4043,
        "longitude": 2.1895,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Bitxus Clínica Veterinaria",
        "description": "Servicios veterinarios de urgencia y tienda especializada cerca de Glòries.",
        "category": "Business",
        "latitude": 41.4060,
        "longitude": 2.1910,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    # --- EL CLOT ---
    {
        "name": "Bodega Sopena",
        "description": "Bodega auténtica del Clot. El lugar perfecto para un vermut con tu perro.",
        "category": "Restaurant",
        "latitude": 41.4082,
        "longitude": 2.1885,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "El Cafè de la Rosa",
        "description": "Cafetería acogedora con pasteles caseros y ambiente muy pet-friendly.",
        "category": "Cafe",
        "latitude": 41.4075,
        "longitude": 2.1870,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Pipican Escultors Claperos",
        "description": "Espacio cerrado muy concurrido por los vecinos del Clot. Muy social.",
        "category": "Pipí can",
        "latitude": 41.4055,
        "longitude": 2.1855,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Jardins de Can Miralletes",
        "description": "Parque histórico con una masía. Zona tranquila para paseos cortos.",
        "category": "Park",
        "latitude": 41.4110,
        "longitude": 2.1815,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "L'Olivera",
        "description": "Restaurante de cocina mediterránea con una terraza muy agradable.",
        "category": "Restaurant",
        "latitude": 41.4090,
        "longitude": 2.1875,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Petardos Clot",
        "description": "Tienda de suministros animales con amplia variedad de piensos naturales.",
        "category": "Store",
        "latitude": 41.4078,
        "longitude": 2.1890,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Orfeó Martinenc",
        "description": "Centro cultural con bar espacioso donde los perros son bien recibidos.",
        "category": "Cafe",
        "latitude": 41.4102,
        "longitude": 2.1852,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Hotel Catalonia Sagrada Familia",
        "description": "Hotel que admite mascotas cerca del Clot. Muy cómodo para visitas.",
        "category": "Lodging",
        "latitude": 41.4095,
        "longitude": 2.1840,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "Plaça de Valentí Almirall",
        "description": "Plaza del ayuntamiento del distrito. Punto de encuentro habitual de perros.",
        "category": "Park",
        "latitude": 41.4072,
        "longitude": 2.1882,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Clínica Veterinaria El Clot",
        "description": "Atención profesional para mascotas en el corazón del barrio.",
        "category": "Business",
        "latitude": 41.4085,
        "longitude": 2.1860,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    # --- CERCA DE LA PLAYA (BOGATELL / MAR BELLA) ---
    {
        "name": "Can Fisher",
        "description": "Restaurante de arroces de alta calidad con terraza que admite perros.",
        "category": "Restaurant",
        "latitude": 41.3975,
        "longitude": 2.2055,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Vai Moana",
        "description": "Chiringuito gastronómico con estilo polinesio. Perros bienvenidos en la terraza.",
        "category": "Restaurant",
        "latitude": 41.3988,
        "longitude": 2.2075,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Espigó del Bogatell",
        "description": "Zona amplia para pasear por el espigón con vistas increíbles.",
        "category": "Park",
        "latitude": 41.3960,
        "longitude": 2.2050,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Bambú Beach Bar",
        "description": "Relájate frente al mar con tu mascota en este chiringuito pet-friendly.",
        "category": "Restaurant",
        "latitude": 41.3995,
        "longitude": 2.2110,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Base Nàutica Municipal",
        "description": "Club náutico que permite el acceso a perros en sus zonas comunes.",
        "category": "Fun",
        "latitude": 41.3950,
        "longitude": 2.2030,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Parc de les Cascades",
        "description": "Parque elevado cerca de la playa con mucha sombra para los días calurosos.",
        "category": "Park",
        "latitude": 41.3895,
        "longitude": 2.1950,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Hotel Arts Barcelona (Zonas externas)",
        "description": "Lujo que admite perros. Sus jardines externos son aptos para pasear.",
        "category": "Lodging",
        "latitude": 41.3885,
        "longitude": 2.1972,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "Passeig Marítim del Bogatell",
        "description": "Kilómetros de paseo junto al mar para disfrutar con tu perro.",
        "category": "Park",
        "latitude": 41.3980,
        "longitude": 2.2085,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Surf House Bogatell",
        "description": "Vibras surferas y platos saludables. Muy populares entre dueños de perros.",
        "category": "Restaurant",
        "latitude": 41.3970,
        "longitude": 2.2065,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Parque del Fòrum (Explanada)",
        "description": "Espacio masivo ideal para que perros grandes corran (atados legalmente).",
        "category": "Park",
        "latitude": 41.4115,
        "longitude": 2.2225,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    # --- LA MARINA (ZONA FRANCA / PRAT VERMELL) ---
    {
        "name": "Parc de la Marina",
        "description": "Enorme parque nuevo con muchas zonas verdes y áreas de juego canino.",
        "category": "Park",
        "latitude": 41.3590,
        "longitude": 2.1385,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Pipican Pg. Zona Franca",
        "description": "Área vallada específica para los perros de la zona de La Marina.",
        "category": "Pipí can",
        "latitude": 41.3610,
        "longitude": 2.1350,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Gran Via 2",
        "description": "Centro comercial cercano muy permisivo con la entrada de perros.",
        "category": "Store",
        "latitude": 41.3595,
        "longitude": 2.1275,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Hotel Leonardo Royal Fira",
        "description": "Hotel moderno en La Marina que acepta mascotas de todos los tamaños.",
        "category": "Lodging",
        "latitude": 41.3575,
        "longitude": 2.1390,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "El Petit Calçot",
        "description": "Restaurante con brasa y terraza pet-friendly en el corazón de la Marina.",
        "category": "Restaurant",
        "latitude": 41.3605,
        "longitude": 2.1402,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Jardins de Can Ferrero",
        "description": "Jardines tranquilos y románticos ideales para un paseo relajado.",
        "category": "Park",
        "latitude": 41.3625,
        "longitude": 2.1415,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Veterinaria La Marina",
        "description": "Servicios médicos cercanos para los vecinos del Prat Vermell.",
        "category": "Business",
        "latitude": 41.3585,
        "longitude": 2.1365,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Bar La Isla",
        "description": "Tapas clásicas en una zona con muchas terrazas aptas para perros.",
        "category": "Restaurant",
        "latitude": 41.3592,
        "longitude": 2.1342,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "IKEA Gran Via",
        "description": "Permite entrada de perros (excepto zona alimentación). Cerca de La Marina.",
        "category": "Store",
        "latitude": 41.3550,
        "longitude": 2.1265,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Plaça del Moviment Obrer",
        "description": "Gran plaza abierta con zonas de descanso para humanos y perros.",
        "category": "Park",
        "latitude": 41.3570,
        "longitude": 2.1375,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    # --- EXTRAS PARA COMPLETAR 50 ---
    {
        "name": "The Hoxton Rooftop",
        "description": "Incluso en la azotea, si vas a comer, suelen permitir perros pequeños.",
        "category": "Restaurant",
        "latitude": 41.4027,
        "longitude": 2.1917,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "L'Esculapi",
        "description": "Pizzería con terraza muy agradable cerca del Clot.",
        "category": "Restaurant",
        "latitude": 41.4115,
        "longitude": 2.1865,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Bar Elkano",
        "description": "Comida casera en un ambiente donde tu perro será uno más.",
        "category": "Restaurant",
        "latitude": 41.4012,
        "longitude": 2.2045,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Pipican Jardins de Ca l'Alier",
        "description": "Zona de recreo moderna junto a una antigua fábrica rehabilitada.",
        "category": "Pipí can",
        "latitude": 41.4072,
        "longitude": 2.1965,
        "allows_unleashed": True,
        "requires_entry_fee": False,
        "is_enclosed": True,
    },
    {
        "name": "Marea Baja",
        "description": "Vistas 360 y picoteo. Aceptan perros en la zona de barra y terraza.",
        "category": "Restaurant",
        "latitude": 41.3830,
        "longitude": 2.1765,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Zoo de Barcelona (Solo perros guía)",
        "description": "Nota: Solo perros de asistencia.",
        "category": "Fun",
        "latitude": 41.3855,
        "longitude": 2.1895,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": True,
    },
    {
        "name": "Dog Is Love",
        "description": "Tienda de accesorios de diseño y chuches naturales en Sant Martí.",
        "category": "Store",
        "latitude": 41.4025,
        "longitude": 2.1982,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "Hotel NH Barcelona Diagonal",
        "description": "Hotel corporativo que permite mascotas bajo petición.",
        "category": "Lodging",
        "latitude": 41.4002,
        "longitude": 2.1925,
        "allows_unleashed": False,
        "requires_entry_fee": True,
        "is_enclosed": False,
    },
    {
        "name": "Parc de Sant Martí",
        "description": "Gran pulmón verde con áreas específicas para perros y mucha sombra.",
        "category": "Park",
        "latitude": 41.4175,
        "longitude": 2.1950,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
    {
        "name": "El Tío Che",
        "description": "La horchatería más famosa. Tómate algo en la terraza con tu perro.",
        "category": "Cafe",
        "latitude": 41.4015,
        "longitude": 2.2035,
        "allows_unleashed": False,
        "requires_entry_fee": False,
        "is_enclosed": False,
    },
]
