pets_data = [
    {
        "name": "Quesito",
        "owner_name": "Rossana",
        "pet_type": "Dog",
        "breed": "Bichon Frise",
        "is_social": True,
        "is_pipican_allowed": True,
        "image_url": "https://images.dog.ceo/breeds/frise-bichon/6.jpg",
    },
    {
        "name": "Ilusiones",
        "owner_name": "Lluís",
        "pet_type": "Dog",
        "breed": "Retriever",
        "is_social": True,
        "is_pipican_allowed": True,
        "image_url": "https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3864.jpg",
    },
    {
        "name": "Pablito",
        "owner_name": "Joan",
        "pet_type": "Dog",
        "breed": "Spitz",
        "is_social": False,  # Pablito es un poco gruñón
        "is_pipican_allowed": True,
        "image_url": "https://images.dog.ceo/breeds/spitz-japanese/beet-001.jpg",
    },
    {
        "name": "Sir FurBall",
        "owner_name": "Marta",
        "pet_type": "Cat",
        "breed": "Persian",
        "is_social": False,
        "is_pipican_allowed": False,  # Los gatos en el pipican... mala idea
        "image_url": "https://placekitten.com/200/300",
    },
    {
        "name": "Rex",
        "owner_name": "BarnaDog",
        "pet_type": "Dog",
        "breed": "Affenpischer",
        "is_social": True,
        "is_pipican_allowed": True,
        "image_url": "https://images.dog.ceo/breeds/affenpinscher/n02110627_12077.jpg",
    },
    {
        "name": "Nana",
        "owner_name": "Luna",
        "pet_type": "Dog",
        "breed": "Border Collie",
        "is_social": True,
        "is_pipican_allowed": True,
        "image_url": "https://images.dog.ceo/breeds/rough-collie/Collie-Rough.jpg",
    },
    {
        "name": "Pagès",
        "owner_name": "Joan",
        "pet_type": "Dog",
        "breed": "Samoyed",
        "is_social": True,
        "is_pipican_allowed": True,
        "image_url": "https://images.dog.ceo/breeds/samoyed/n02111889_2650.jpg",
    },
    {
        "name": "Miracle",
        "owner_name": "Rossana",
        "pet_type": "Dog",
        "breed": "Shihtzu",
        "is_social": True,
        "is_pipican_allowed": True,
        "image_url": "https://images.dog.ceo/breeds/shihtzu/n02086240_9467.jpg",
    },
]
