# Generated by Django 6.0.3 on 2026-03-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], default='Dog', max_length=5)),
                ('breed', models.CharField(default='mixed', max_length=30)),
                ('is_social', models.BooleanField(default=True)),
                ('is_pipican_allowed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetWalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poops', models.IntegerField(default=0)),
                ('pees', models.IntegerField(default=0)),
                ('mood', models.CharField(choices=[('As usual', 'As Usual'), ('Happy', 'Happy'), ('Sad', 'Sad'), ('Anxious', 'Anxious'), ('Lethargic', 'Lethargic'), ('Tired', 'Tired')], default='As usual', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pets', models.ManyToManyField(through='core.PetWalk', to='core.pet', verbose_name='list of pets')),
            ],
        ),
        migrations.AddField(
            model_name='petwalk',
            name='walk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.walk'),
        ),
        migrations.CreateModel(
            name='WalkPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.walk')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
