# Generated by Django 6.0.3 on 2026-03-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_place_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetWalk',
            new_name='PetWalkDetail',
        ),
    ]
