# Generated by Django 6.0.3 on 2026-03-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_petwalk_petwalkdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Lodging', 'Lodging'), ('Cafe', 'Cafe'), ('Restaurant', 'Restaurant'), ('Park', 'Park'), ('Pipí can', 'Pipi Can'), ('Fun', 'Fun'), ('Business', 'Business'), ('Store', 'Store')], default='Business'),
        ),
        migrations.AlterField(
            model_name='petwalkdetail',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='core.pet'),
        ),
        migrations.AlterField(
            model_name='petwalkdetail',
            name='walk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.walk'),
        ),
    ]
