# Generated by Django 6.0.3 on 2026-03-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_place_category_alter_petwalkdetail_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petwalkdetail',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.pet'),
        ),
    ]
