# Generated by Django 6.0.3 on 2026-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_review_note_alter_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
